#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
YO Contest Judge PRO — Calendar Concursuri YO 2026
Sursa: radioamator.ro/contest/
Contine toate concursurile din calendarul competitional 2026 cu link-uri la regulamente.
"""

CALENDAR_2026 = [
    # Ianuarie
    {"date":"02 IAN",  "name":"La multi ani YO!",
     "url":"https://www.radioamator.ro/contest/us/la_multi_ani_yo.pdf",
     "organizer":"FRR", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"10 IAN",  "name":"Cupa Municipiului Campina",
     "url":"https://www.radioamator.ro/contest/us/cupa_campina.pdf",
     "organizer":"YO9KPB", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"10 IAN",  "name":"Cupa Podul Inalt",
     "url":"https://www.radioamator.ro/contest/us/cupa_podul_inalt.pdf",
     "organizer":"YO8KVS", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"18 IAN",  "name":"Memorial YO2RA",
     "url":"https://www.radioamator.ro/contest/us/memorial_yo2ra.pdf",
     "organizer":"C.S. Admira", "type":"HF", "band":"80m", "mode":"SSB"},
    # Februarie
    {"date":"16 FEB",  "name":"Cupa Moldovei",
     "url":"https://www.radioamator.ro/contest/us/cupa_moldovei.pdf",
     "organizer":"YO8KAN", "type":"HF", "band":"80m", "mode":"SSB/CW"},
    {"date":"23 FEB",  "name":"Cupa Tomis",
     "url":"https://www.radioamator.ro/contest/us/cupa_tomis.pdf",
     "organizer":"Asociatia Radioclubul Radu Bratu", "type":"HF", "band":"80m", "mode":"SSB"},
    # Martie
    {"date":"02-15 MAR","name":"Maratonul International Radio Ion Creanga",
     "url":"https://www.radioamator.ro/contest/us/maraton_ion_creanga.pdf",
     "organizer":"YO8KZG", "type":"HF", "band":"80m", "mode":"SSB",
     "contest_id":"maraton_ic"},
    {"date":"02 MAR",  "name":"Campionatul National US - radiotelegrafie etapa I",
     "url":"https://www.hamradio.ro/CNUSCW/regulament.php",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"CW"},
    {"date":"09 MAR",  "name":"Campionatul National US - radiotelegrafie etapa II",
     "url":"https://www.hamradio.ro/CNUSCW/regulament.php",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"CW"},
    {"date":"23 MAR",  "name":"Radio-Club Craiova CV5",
     "url":"https://www.radioamator.ro/contest/us/radio_craiova.pdf",
     "organizer":"YO7KAJ", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"30 MAR",  "name":"Cupa Elevului",
     "url":"https://www.radioamator.ro/contest/us/cupa_elevilor.pdf",
     "organizer":"Palatul Copiilor Piatra Neamt", "type":"HF", "band":"80m", "mode":"SSB"},
    # Aprilie
    {"date":"04 APR",  "name":"Cupa OTCR",
     "url":"https://www.radioamator.ro/contest/us/cupa_otc.pdf",
     "organizer":"FRR, CSR Oravita", "type":"HF", "band":"80m", "mode":"SSB/CW"},
    {"date":"06 APR",  "name":"Trofeul Carpati",
     "url":"https://www.radioamator.ro/contest/us/trofeul_carpati_us.pdf",
     "organizer":"YO6KAF", "type":"HF", "band":"multi", "mode":"SSB/CW"},
    # Mai
    {"date":"09 MAI",  "name":"Concursul Lucian Blaga",
     "url":"https://www.radioamator.ro/contest/us/lucian_blaga.pdf",
     "organizer":"YO5KLB", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"11 MAI",  "name":"Cupa Telecomunicatiilor",
     "url":"https://www.radioamator.ro/contest/us/cupa_telecomunicatiilor_us.pdf",
     "organizer":"C.S. Silver Fox Deva", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"18 MAI",  "name":"Cupa Brailei",
     "url":"https://www.radioamator.ro/contest/us/cupa_brailei.pdf",
     "organizer":"CSR Braila", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"21 MAI",  "name":"Cupa Aviatiei (ziua I)",
     "url":"https://www.radioamator.ro/contest/us/cupa_aviatiei.pdf",
     "organizer":"CSU Pitesti", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"25 MAI",  "name":"Cupa Municipiului Pitesti US",
     "url":"https://www.radioamator.ro/contest/us/cupa_municipiului_pitesti.pdf",
     "organizer":"YO7KFA", "type":"HF", "band":"80m", "mode":"SSB"},
    # Iulie
    {"date":"11 IUL",  "name":"Cupa Transmisionistului",
     "url":"https://www.radioamator.ro/contest/us/cupa_transmisionistului.pdf",
     "organizer":"YO6KNW", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"20 IUL",  "name":"Cupa Aviatiei (ziua II)",
     "url":"https://www.radioamator.ro/contest/us/cupa_aviatiei.pdf",
     "organizer":"CSU Pitesti", "type":"HF", "band":"80m", "mode":"SSB"},
    # August
    {"date":"22-23 AUG","name":"Campionatul National US Multiband (YO DX HF Contest)",
     "url":"https://www.hamradio.ro/wp-content/uploads/2024/01/Regulament-YODX-si-CNUSMB.pdf",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"SSB/CW",
     "contest_id":"yodxhf"},
    # Octombrie
    {"date":"05 OCT",  "name":"Campionatul National US - radiotelefonie etapa I",
     "url":"https://www.hamradio.ro/CNUSSSB/regulament.php",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"SSB"},
    {"date":"12 OCT",  "name":"Campionatul National US - radiotelefonie etapa II",
     "url":"https://www.hamradio.ro/CNUSSSB/regulament.php",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"SSB"},
    {"date":"17 OCT",  "name":"Cupa 25 Octombrie",
     "url":"https://www.radioamator.ro/contest/us/cupa_25_octombrie.pdf",
     "organizer":"YO6KNW", "type":"HF", "band":"80m", "mode":"SSB"},
    # Noiembrie
    {"date":"02 NOV",  "name":"Memorial YO",
     "url":"https://www.radioamator.ro/contest/us/memorial_yo.pdf",
     "organizer":"FRR", "type":"HF", "band":"multi", "mode":"SSB/CW"},
    {"date":"07 NOV",  "name":"Cupa Feroviarului - Memorial YO2BV",
     "url":"https://www.radioamator.ro/contest/us/cupa_feroviarului.pdf",
     "organizer":"YO5KUF", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"23 NOV",  "name":"Cupa Bucovinei",
     "url":"https://www.radioamator.ro/contest/us/cupa_bucovinei.pdf",
     "organizer":"YO8KGA", "type":"HF", "band":"80m", "mode":"SSB"},
    # Decembrie
    {"date":"01 DEC",  "name":"Cupa 1 Decembrie",
     "url":"https://www.radioamator.ro/contest/us/cupa_1dec.pdf",
     "organizer":"Asociatia Judeteana Alba", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"07 DEC",  "name":"Cupa Silver Fox US",
     "url":"https://www.radioamator.ro/contest/us/cupa_silver_fox.pdf",
     "organizer":"CS Silver Fox Deva", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"14 DEC",  "name":"Cupa Minoritatilor",
     "url":"https://www.radioamator.ro/contest/us/cupa_minoritatilor.pdf",
     "organizer":"YO4KAK", "type":"HF", "band":"80m", "mode":"SSB"},
    {"date":"26 DEC",  "name":"Obiceiuri de Craciun la Limba",
     "url":"https://www.radioamator.ro/contest/us/obiceiuri_craciun_limba.pdf",
     "organizer":"YO5KAL", "type":"HF", "band":"80m", "mode":"SSB"},
    # VHF/UHF
    {"date":"18-19 APR","name":"Cupa Romaniei in Unde Ultrascurte Etapa I",
     "url":"https://www.radioamator.ro/contest/uus/cupa_romaniei_uus.pdf",
     "organizer":"FRR", "type":"VHF", "band":"2m/70cm", "mode":"SSB/FM/CW"},
    {"date":"16-17 MAI","name":"Cupa Romaniei in Unde Ultrascurte Etapa II",
     "url":"https://www.radioamator.ro/contest/uus/cupa_romaniei_uus.pdf",
     "organizer":"FRR", "type":"VHF", "band":"2m/70cm", "mode":"SSB/FM/CW"},
    {"date":"20-21 IUN","name":"Cupa Romaniei in Unde Ultrascurte Etapa III",
     "url":"https://www.radioamator.ro/contest/uus/cupa_romaniei_uus.pdf",
     "organizer":"FRR", "type":"VHF", "band":"2m/70cm", "mode":"SSB/FM/CW"},
    {"date":"04-05 IUL","name":"Campionatul International UUS al Romaniei YO-VHF/UHF",
     "url":"https://www.radioamator.ro/contest/uus/yodx_vhf_uhf_shf.pdf",
     "organizer":"FRR", "type":"VHF", "band":"multi", "mode":"SSB/CW"},
    {"date":"19-20 SEP","name":"Cupa Romaniei in Unde Ultrascurte Etapa IV",
     "url":"https://www.radioamator.ro/contest/uus/cupa_romaniei_uus.pdf",
     "organizer":"FRR", "type":"VHF", "band":"2m/70cm", "mode":"SSB/FM/CW"},
]

CALENDAR_SOURCE = "https://www.radioamator.ro/contest/"
